### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by alxdb** [peterakirk/RapidHRV#5]

**Comment by alxdb** [comment]
* plotly
* notebooks

**Comment by peterakirk** [comment]
@alxdb, two final things: could change it so it doesn't give us the debugging output in the terminal please? Also, please let me know if you have a chance to implement the code coverage.

Side-note: running Dash with the debug mode on will crash in Pycharm 2021.1.3 (https://stackoverflow.com/questions/69910390/why-does-dash-throw-a-typeerror-when-debugging-through-pycharm). An update to 2021.2.4 fixes this.

**Comment by alxdb** [comment]
the route logging (all the GET and POST logs) can be disabled easily with a switch, I'll add that in a PR.

Also noticed a few issues when messing with the app to do with the selected point:
- Selected point remains when changing selected series
- Can't deselect point (issue?)
- Selected point has a generic label (trace 2)

Looking at that traceback, the issue is something to do with the filesystem, when in debug mode, the server watches your source files to know when to reload (i.e. when you change them).

I'll make another issue for adding code coverage to the CI

**Comment by peterakirk** [comment]
Additional issue: selecting a datapoint resets the zoom. Ok for small datasets, more of a problem for large amounts of data.

**Comment by peterakirk** [comment]
There seems to be a discrepancy of 1 index between the plotted window of of extraction in dash/plotly and the actual signal recorded in the analyzed output signal. Left image: dash selection at time point 30 seconds; right image: plot of output at 20 seconds analyzed[2,"Window"][0]. I'll try and get round to fixing this later today. 
![Screenshot 2022-01-19 085221](https://user-images.githubusercontent.com/50597200/150087789-5eaf7bb6-f90e-4fd9-add4-1a35b237f8aa.png)

**Comment by peterakirk** [comment]
> There seems to be a discrepancy of 1 index between the plotted window of of extraction in dash/plotly and the actual signal recorded in the analyzed output signal. Left image: dash selection at time point 30 seconds; right image: plot of output at 20 seconds analyzed[2,"Window"][0]. I'll try and get round to fixing this later today.

Fixed. This seemed to be an issue of having two plots (non_outliers and outliers). The click data was returning the index relative to plot selected, but not the exact timepoint collapsed across all analyzed data.

**Comment by peterakirk** [comment]
Currently re-submitting the manuscript today. Should we address the below warning? Once this is sorted we can deploy to PyPI.

>  * Serving Flask app '<input>' (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off

**Comment by alxdb** [comment]
It is kind of annoying that it’s there but it’s unimportant, it’s to do
with actually hosting on a server which we aren’t doing.

I might be able to make it go away, let me take a look

**Comment by peterakirk** [comment]
No need to spend any time on it. Would you be ok uploading this to PyPI? Just finishing up all the manuscript formatting etc. now.

**Comment by alxdb** [comment]
There's no neat way to remove the warning

I need your login details to upload to pypi
